export const recipeData = [
    {
        id: 1,
        name:"Steak and Cheese Wraps",
        category: "",
        description: "",
        ingredients: ["Shaved Steak", "Cheese", "Wrap", "Various Colored Peppers", "Onion"],
    },
    {
        id: 2,
        name:"Breakfast for Dinner",
        category: "",
        description: "",
        ingredients: ["Eggs", "Diced Potatoes", "Sausage", "Bacon"],
    },
    {
        id: 3,
        name:"Scrambled Eggs",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 4,
        name:"Quesadillas",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 5,
        name:"Homemade Chicken Tenders",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 6,
        name:"Lemon Chicken Orzo",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 7,
        name:"Steak and Cheese Stuffed Peppers",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 8,
        name:"Mini Build Your Own Pizza",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 9,
        name:"Meatloaf",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 10,
        name:"BBQ Meatloaf",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 11,
        name:"Grilled Cheese",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 12,
        name:"Buffalo Chicken Grilled Cheese",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 13,
        name:"Buffalo Chicken Dip",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 14,
        name:"Shepard's Pie",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 15,
        name:"Tacos",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 16,
        name:"Enchiladas",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 17,
        name:"Pasta and Meatballs",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 18,
        name:"Nachos",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 19,
        name:"Burger",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 20,
        name:"Chili",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 21,
        name:"Lasagna",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 22,
        name:"Pulled BBQ Chicken Sandwiches",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 23,
        name:"Mini Burger Sliders",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 24,
        name:"Chicken and Veggie Stir-Fry",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 25,
        name:"Chicken Broccoli Alfredo",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 26,
        name:"Mac and Cheese",
        category: "",
        description: "",
        ingredients: ["Macaroni Pasta", "Cheese"],
    },
    {
        id: 27,
        name:"Buffalo Mac and Cheese",
        category: "",
        description: "",
        ingredients: ["Macaroni Pasta", "Cheese", "Buffalo Sauce"],
    },
    {
        id: 28,
        name:"Chicken Tender Wraps",
        category: "",
        description: "",
        ingredients: ["Chicken", "Shredded Cheese", "Wraps"],
    },
    {
        id: 29,
        name:"Hot Dogs and Beans",
        category: "",
        description: "",
        ingredients: ["Hot Dogs", "Hot Dog Buns", "Baked Beans"],
    },
    {
        id: 30,
        name:"Pork Chops",
        category: "",
        description: "",
        ingredients: ["", ""],
    },
    {
        id: 31,
        name:"Bagels",
        category: "",
        description: "",
        ingredients: ["Bagels", "Cream Cheese"],
    },
    {
        id: 32,
        name:"Mozzarella Sticks",
        category: "",
        description: "",
        ingredients: ["Low-moisture Mozzarella Cheese", "Flour", "Sea Salt", "Pepper", "Garlic Powder", "Eggs", "Panko", "Italian Seasoning"],
    },
    {
        id: 33,
        name:"Broccoli",
        category: "",
        description: "",
        ingredients: ["Broccoli"],
    },
    {
        id: 34,
        name:"Diced Sweet Potatoes",
        category: "",
        description: "",
        ingredients: ["Sweet Potatoes"],
    },
    {
        id: 35,
        name:"Baked Sweet Potato",
        category: "",
        description: "",
        ingredients: ["Sweet Potato"],
    },
    {
        id: 36,
        name:"Baked Potato",
        category: "",
        description: "",
        ingredients: ["Potato"],
    },
    {
        id: 37,
        name:"French Toast",
        category: "",
        description: "",
        ingredients: ["Bread", "Eggs", "Cinnamon"],
    },
    {
        id: 38,
        name:"Steamed White Rice",
        category: "",
        description: "",
        ingredients: ["White Rice"],
    },
    {
        id: 39,
        name:"Waffles",
        category: "",
        description: "",
        ingredients: ["Eggs", "Flour", "White Sugar", "Milk", "Baking Powder", "Salt", "Vanilla Extract", "Butter"],
    },
    {
        id: 40,
        name:"Risotto",
        category: "",
        description: "",
        ingredients: ["Arborio Rice", "Chicken Stock", "Vegetable Oil", "Butter", "Medium Shallot", "Dry White Wine", "Parmesan Cheese", "Italian Parsley", "Kosher Salt", "Black Pepper"],
    },
]